### ISSUE TITLE
quantity of the order and containers

### ISSUE THREAD

**Issue by leenong75cn** [gyang274/gbp#2]
Hi gyang274:

   I'm on a project to solve a bin packing problem. and I tried you Rscript GBP. I feels the packing works great. Thanks for that.

  however I encountered several problems, plz advice, thanks ahead

  1. is there a way that I can defined the quantity of the orders and containers? Because in my projects I need to pack multiple produces with the same size. and multiple same sized containers
  2.  can i define, dont let the products rotate, cause some products had to be face up.
  3.  can i define packing priority, cause some sku need to go first

 I know i have many questions, thanks ahead, again, this is a great package, deeply appreciated

best

Ning

**Comment by gyang274** [comment]
Hi, @leenong75cn 

1. You have to manually replicated the multiple items (products). There is no limit in the number of bins (containers) in the current algorithm. 

2.  This is a preferred feature. However, the current algorithm assumes all items can be rotated freely. You have to modify the RCpp code.

3. In the current algorithm, the order is dynamic, e.g. skus go next depends on the current fit structure. There is a scoring function to determine which sku go next can make the rest of available space more unified. As a result, we can not determine the packing sequence beforehand.

Thank you.

Best Regards,
gyang274

**Comment by leenong75cn** [comment]
THank you so much for the reply. Your coding is really wonderful. Thanks
